ALTER TABLE flyway.person ADD COLUMN age INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS flyway.business (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name varchar(100) NOT NULL
);