-- Script generated by Redgate Compare v1.28.0.25641
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating flyway.person.country...';END$$;
ALTER TABLE flyway.person ADD COLUMN country character varying NOT NULL DEFAULT 0;

SET check_function_bodies = true;
